version: '3.9'
services:
  vlxd-api:
    container_name: backend
    build: ./vlxd-api
    env_file:
      - .env.api
    ports:
      - 5000:5000
    expose:
      - 5000 
    networks:
      - vlxd
  mongo-container:
    image: mongo
    container_name: mongo-container
    ports:
      - 27018:27017
    volumes:
      - ./vlxd-mongo-db:/data/db
    networks:
      - vlxd
  vlxd-client:
    container_name: frontend 
    build: 
      dockerfile: Dockerfile
      context: ./vlxd-client  
    ports:
      - 3001:80
    networks:
      - vlxd
networks:
  vlxd:
    name: vlxd-network    
