version: '3'
services:
  vlxd-api:
    container_name: vlxd-api-container
    build: 
      dockerfile: Dockerfile
      context: ./vlxd-api
    env_file:
      - .env.api
    ports:
      - 5000:5000
    volumes:
      - ./vlxd-api:/app/vlxd-api
    networks:
      - vlxd
  mongo-container:
    image: mongo
    container_name: mongo-container
    ports:
      - 27018:27017
    volumes:
      - ./vlxd-mongo-db:/data/db
    networks:
      - vlxd
  vlxd-client:
    container_name: vlxd-client-container
    build: 
      dockerfile: Dockerfile
      context: ./vlxd-client
    env_file:
      - .env.client
    ports:
      - 3001:3000
    volumes:
      - ./vlxd-client:/app/vlxd-client 
    networks:
      - vlxd 
  nginx:
    image: nginx:1.23.3
    ports:
      - 3000:80
    volumes:
      - ./vlxd-client/build:/usr/share/nginx/html
      - ./vlxd-client/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  vlxd:
    name: vlxd-network    
