version: '3.9'
services:
  vlxd-api:
    container_name: vlxd-api-container
    build: ./vlxd-api
    env_file:
      - .env.api
    ports:
      - 5000:5000
    # volumes:
    #   - ./vlxd-api:/app
    networks:
      - vlxd
  mongo-container:
    image: mongo
    container_name: mongo-container
    ports:
      - 27018:27017
    volumes:
      - ./vlxd-mongo-db:/data/db
    networks:
      - vlxd
  vlxd-client:
    container_name: vlxd-client-container
    restart: on-failure
    build: 
      dockerfile: Dockerfile
      context: ./vlxd-client
    env_file:
      - .env.client
    ports:
      - 3001:80 
    networks:
      - vlxd  
networks:
  vlxd:
    name: vlxd-network    
